name: Update Website

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch the full history, to build attribution.json
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: yarn

      - uses: microsoft/playwright-github-action@v1

      # Builds the modules, and boostraps the other modules
      - name: Build website
        run: |
          export YARN_ENABLE_IMMUTABLE_INSTALLS=false
          yarn install
          yarn bootstrap
          yarn build
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      # Builds the site
      - name: Makes the site
        run: |
          yarn build-site
          cp -r packages/lingua-franca/public site
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      # Checks for known security vulnerabilities
      - uses: GuillaumeFalourd/assert-command-line-output@v2
        with:
          command_line: yarn npm audit
          contains: No audit suggestions
          expected_result: PASSED

      # Deploy to lf-lang.org
      - name: Deploy + Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          cname: www.lf-lang.org
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: "gh-pages"
          publish_dir: ./site
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
